version: '3.8'

services:
  linux-server-manager:
    build: .
    container_name: linux-server-manager
    ports:
      - "8080:80"
    volumes:
      - ./logs:/var/www/html/logs
      - ./config:/var/www/html/config
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    restart: unless-stopped
    networks:
      - app-network

  # Опционально: база данных (если понадобится в будущем)
  # mysql:
  #   image: mysql:8.0
  #   container_name: lsm-mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: linux_server_manager
  #     MYSQL_USER: lsm_user
  #     MYSQL_PASSWORD: lsm_password
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - app-network
  #   restart: unless-stopped

  # Опционально: Redis для кеширования
  # redis:
  #   image: redis:7-alpine
  #   container_name: lsm-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - app-network
  #   restart: unless-stopped

networks:
  app-network:
    driver: bridge

# volumes:
#   mysql_data:
#   redis_data:
